site_name: MJS AI Assistants Catalog
site_description: Internal catalog of approved AI developer assistants

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Assistants:
    - Code Review Assistants: assistants/code-review.md
    - C# API & Entity Framework Assistant: assistants/csharp-api-entity-framwork.md
    - C# .NET Upgrade Assistant: assistants/csharp-dotnet-upgrade.md
    - .Net API Architect Assistant: assistants/dotnet-api-architect.md
    - C# Expert Assistant: assistants/csharp-expert.md
    - Dynatrace Expert Assistant: assistants/dynatrace-expert.md
    - MudBlazor Assistant: assistants/mudblazor.md


